version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/deploy/
hooks:
  AfterInstall:
    - location: scripts/wpdeploy.sh
      timeout: 300
      runas: root
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
      
